# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.0.1rc8.dev209+g22eaea2.d20221118"
__version_tuple__ = version_tuple = (0, 0, 1, "dev209", "g22eaea2.d20221118")
