name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request: {}
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uvx check-manifest

  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }} ${{ matrix.backend }} ${{ matrix.resolution }}
    runs-on: ${{ matrix.os }}
    env:
      UV_NO_SYNC: "1"
      UV_MANAGED_PYTHON: "1"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.10", "3.13"]
        backend: [PyQt6]
        resolution: ["highest", "lowest-direct"]
        exclude:
          - os: macos-latest
            resolution: lowest-direct
        include:
          - os: windows-latest
            python-version: "3.12"
            backend: PyQt6
          - os: windows-latest
            python-version: "3.13"
            backend: PySide6
            resolution: highest
          - os: macos-latest
            python-version: "3.13"
            backend: PySide6
            resolution: lowest-direct

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - uses: pyvista/setup-headless-display-action@v4

      - name: Install dependencies
        run: uv sync --no-dev --group test --extra ${{ matrix.backend }}

      - uses: pymmcore-plus/setup-mm-test-adapters@main

      - name: Test
        run: uv run coverage run -p -m pytest -v --color=yes
        env:
          PYTEST_ADDOPTS: ${{ matrix.resolution == 'lowest-direct' && '-W ignore' || '' }}

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: covreport-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.backend }}-${{ matrix.resolution }}
          path: ./.coverage*
          include-hidden-files: true

  upload_coverage:
    if: always()
    needs: [test]
    uses: pyapp-kit/workflows/.github/workflows/upload-coverage.yml@v2
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    name: Deploy
    needs: test
    if: ${{ github.repository == 'pymmcore-plus/napari-micromanager' && contains(github.ref, 'tags') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: 👷 Build
        run: uv build

      - name: 🚢 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: "./dist/*"
